Center/api/urls.py
from django.urls import path ,include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()

router.register('degree/', degree_view)
router.register('subject/', subject_view)
router.register('specification/', spiecification_view)
router.register('service/', service_view)
router.register('project/', project_view)
router.register('task-project/', task_project_view)

urlpatterns = [

    path('', include(router.urls))

]

Mustasharc/urls.py
from django.contrib import admin
from django.urls import path, include
from Mustasharc import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/', include('Mustasharc.api')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('home.urls', namespace="home")),
    path('blog/', include('blog.urls',namespace="blog"))

]+  static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import posts,post

app_name = "blog"
urlpatterns= [
    path("", posts,  name="posts"),
    path("<str:title>/", post,  name="post"),
]

home/urls.py
from django.urls import path


from .views import home, services
app_name = 'home'
urlpatterns = [
    path('', home,  name="homepage"),
    path('services/', services, name="services"),
]

orders/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *
router = DefaultRouter()

router.register('phoneorder/',phoneorder_view)
router.register('orderwork/',orderwork_view)


urlpatterns = [
    path('', include(router.urls))
]

Center/models.py
from django.db import models
from django_countries.fields import CountryField


class Degree(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Subject(models.Model):
    subject = models.CharField(max_length=50)

    def __str__(self):
        return self.subject


class Spiecification(models.Model):
    degree = models.ForeignKey(Degree, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.subject.subject} - {self.degree.name}'


class Service(models.Model):
    service = models.CharField(max_length=50)
    spiecification = models.ForeignKey(
        Spiecification, on_delete=models.CASCADE, related_name='spiecification_service', blank=True,null=True)

    def __str__(self):
        return f'{self.service} - {self.spiecification.degree.name} - {self.spiecification.subject.subject}'


class Project(models.Model):
    project = models.CharField(max_length=50)
    spiecification = models.ForeignKey(Spiecification, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.project} - {self.spiecification}"


class TaskProject(models.Model):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="taskproject")
    task = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.task} - {self.project.project}'


class Country(models.Model):
    country = CountryField()

    def __str__(self):
        return self.country.name


class Bank(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    Bank = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.Bank


class NumberAccount(models.Model):
    Bank = models.ForeignKey(Bank, on_delete=models.CASCADE)
    NumberOfAccount = models.IntegerField()
    NameOfAccount = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.Bank.Bank} - account -{self.pk}'

blog/models.py
from django.db import models
from Center.models import *
from ckeditor.fields import RichTextField

class SEO(models.Model):
    head= models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    img = models.ImageField(upload_to='blog/',blank=True, null=True)
    keyword = models.JSONField()

class Description(models.Model):
    img = models.ImageField(upload_to='blog/description/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    body = RichTextField()


class degree_desc(models.Model):
    seo = models.OneToOneField(SEO, on_delete=models.CASCADE)
    degree = models.ForeignKey(Degree , on_delete=models.CASCADE)
    description = models.OneToOneField(Description, on_delete=models.CASCADE)


class subject_desc(models.Model):
    seo = models.OneToOneField(SEO, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject , on_delete=models.CASCADE)
    description = models.OneToOneField(Description, on_delete=models.CASCADE)


class spiecification_desc(models.Model):
    seo = models.OneToOneField(SEO, on_delete=models.CASCADE)
    spiecification = models.ForeignKey(Spiecification , on_delete=models.CASCADE)
    description = models.OneToOneField(Description, on_delete=models.CASCADE)


class service_desc(models.Model):
    seo = models.OneToOneField(SEO, on_delete=models.CASCADE)
    service = models.ForeignKey(Service , on_delete=models.CASCADE)
    description = models.OneToOneField(Description, on_delete=models.CASCADE)


class project_desc(models.Model):
    seo = models.OneToOneField(SEO, on_delete=models.CASCADE)
    project = models.ForeignKey(Project , on_delete=models.CASCADE)
    description = models.OneToOneField(Description, on_delete=models.CASCADE)


class task_project_desc(models.Model):
    seo = models.OneToOneField(SEO, on_delete=models.CASCADE)
    task_project = models.ForeignKey(TaskProject , on_delete=models.CASCADE)
    description = models.OneToOneField(Description, on_delete=models.CASCADE)

home/models.py
from django.db import models

orders/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from Center.models import Service
# Create your models here.

class phoneorder(models.Model):
    phone = PhoneNumberField()

    def __str__(self):
        return self.phone

class orderwork(models.Model):
    service = models.ForeignKey(Service,on_delete=models.CASCADE, blank=True,null=True)
    email = models.EmailField(blank=True)
    phone_number = PhoneNumberField()
    text = models.TextField()

    def __str__(self):
        return f'{self.service} - {self.phone_number}'

Center/api/views.py
from rest_framework.viewsets import ModelViewSet
from ..models import Degree, Subject, Spiecification, Service, Project, TaskProject
from rest_framework.permissions import AllowAny
from .serializers import *


class degree_view(ModelViewSet):
    queryset = Degree.objects.all()
    serializer_class = DegreeSerializers
    permission_classes = [AllowAny]


class subject_view(ModelViewSet):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializers
    permission_classes = [AllowAny]


class spiecification_view(ModelViewSet):
    queryset = Spiecification.objects.all()
    serializer_class = SpiecificationSerializers
    permission_classes = [AllowAny]


class service_view(ModelViewSet):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializers
    permission_classes = [AllowAny]


class project_view(ModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializers
    permission_classes = [AllowAny]


class task_project_view(ModelViewSet):
    queryset = TaskProject.objects.all()
    serializer_class = TaskProjectSerializers
    permission_classes = [AllowAny]

blog/views.py
from django.shortcuts import render


# Create your views here.
def posts(request):
    return render(request, 'home/posts.html')


def post(request, title):
    return render(request, 'home/post.html')

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home/index.html')

def services(request):
    return render(request , 'home/services.html')

orders/api/views.py
from rest_framework.viewsets import ModelViewSet
from ..models import phoneorder, orderwork
from .serializers import *


class phoneorder_view(ModelViewSet):
    queryset = phoneorder.objects.all()
    serializer_class = phoneorderSerializer


class orderwork_view(ModelViewSet):
    queryset = orderwork.objects.all()
    serializer_class = orderworkSerializer

orders/views.py
from django.shortcuts import render

# Create your views here.

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <title>Mustasharc - مستشارك</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">


    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="https://di7nobqb0ovd3.cloudfront.net/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="https://di7nobqb0ovd3.cloudfront.net/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="https://di7nobqb0ovd3.cloudfront.net/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="https://di7nobqb0ovd3.cloudfront.net/static/css/style.css" rel="stylesheet">
</head>
<body>
    <div class="position-relative bg-white d-flex p-0">
        {% include 'members/spinner.html' %}
        {% include 'members/sidebar.html' %}

        <div class="content">

            {% include 'members/navbar.html' %}

            {% block content %}

            {% endblock %}
            {% include 'members/footer.html' %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/chart/chart.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/easing/easing.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/waypoints/waypoints.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/tempusdominus/js/moment.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="https://di7nobqb0ovd3.cloudfront.net/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="
    https://di7nobqb0ovd3.cloudfront.net/static/js/main.js"></script>
</body>
</html>

home/templates/home/blog.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

home/templates/home/chart.html
            <!-- Chart Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Single Line Chart</h6>
                            <canvas id="line-chart"></canvas>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Multiple Line Chart</h6>
                            <canvas id="salse-revenue"></canvas>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Single Bar Chart</h6>
                            <canvas id="bar-chart"></canvas>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Multiple Bar Chart</h6>
                            <canvas id="worldwide-sales"></canvas>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Pie Chart</h6>
                            <canvas id="pie-chart"></canvas>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Doughnut Chart</h6>
                            <canvas id="doughnut-chart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Chart End -->

home/templates/home/library.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

home/templates/home/post.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

home/templates/home/posts.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

home/templates/home/services.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

home/templates/home/signin.html
{% extends 'baseAuth.html' %}
{% block content %}
       <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
                <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    <div class="bg-light rounded p-4 p-sm-5 my-4 mx-3">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <a href="index.html" class="">
                                <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>DASHMIN</h3>
                            </a>
                            <h3>Sign In</h3>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                            <label for="floatingInput">Email address</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
                            <a href="">Forgot Password</a>
                        </div>
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Sign In</button>
                        <p class="text-center mb-0">Don't have an Account? <a href="">Sign Up</a></p>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

home/templates/home/signup.html
{% extends 'baseAuth.html' %}
{% block content %}
      <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
                <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    <div class="bg-light rounded p-4 p-sm-5 my-4 mx-3">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <a href="index.html" class="">
                                <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>DASHMIN</h3>
                            </a>
                            <h3>Sign Up</h3>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="floatingText" placeholder="jhondoe">
                            <label for="floatingText">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                            <label for="floatingInput">Email address</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
                            <a href="">Forgot Password</a>
                        </div>
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Sign Up</button>
                        <p class="text-center mb-0">Already have an Account? <a href="">Sign In</a></p>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

home/templates/members/backtotop.html
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

home/templates/members/footer.html
 <div class="container-fluid pt-4 px-4 w-100" style="background-color: #042d2d;
 color:white">
                <div class="p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                             <a href="#" class="h3 text-light">مستشارك</a>&copy;,جميع الحقوق محفوظة.
                        </div><br/>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                           تم التصميم من قبل <a href="https://mu3tamad.com">المعتمد</a>
                        </br>
<!--                        Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>-->
                        </div>
                    </div>
                </div>
            </div>

home/templates/members/navbar.html
<nav class="navbar navbar-expand  navbar-dark sticky-top px-4 py-0 text-center" style="background-color: #178080">
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars" style="color: white;"></i>
                </a>
                <a href="index.html" class="navbar-brand d-flex align-items-center mx-auto">
                    <h2 class="text-light gab-2 mb-0"><img src="/static/img/logo.png" class="mx-2 " style="max-height: 40px;"/><span class="d-lg-inline-flex ">مستشارك</span></h2>
                </a>

                <div class="navbar-nav align-items-center">
<!--                     {% if user.is_authenticated %}-->
<!--                        <div class="nav-item dropdown rounded-pillow">-->
<!--                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">-->
<!--                                <i class="fa fa-envelope me-lg-2"></i>-->
<!--                                <span class="d-none d-lg-inline-flex">Message</span>-->
<!--                            </a>-->
<!--                            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">-->
<!--                                <a href="#" class="dropdown-item">-->
<!--                                    <div class="d-flex align-items-center">-->
<!--                                        <img class="rounded-circle" src="/static/img/user.jpg" alt="" style="width: 40px; height: 40px;">-->
<!--                                        <div class="me-2">-->
<!--                                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>-->
<!--                                            <small>15 minutes ago</small>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                                <hr class="dropdown-divider">-->
<!--                                <a href="#" class="dropdown-item ">-->
<!--                                    <div class="d-flex align-items-center">-->
<!--                                        <img class="rounded-circle" src="/static/img/user.jpg" alt="" style="width: 40px; height: 40px;">-->
<!--                                        <div class="me-2">-->
<!--                                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>-->
<!--                                            <small>15 minutes ago</small>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                                <hr class="dropdown-divider">-->
<!--                                <a href="#" class="dropdown-item">-->
<!--                                    <div class="d-flex align-items-center">-->
<!--                                        <img class="rounded-circle" src="/static/img/user.jpg" alt="" style="width: 40px; height: 40px;">-->
<!--                                        <div class="me-2">-->
<!--                                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>-->
<!--                                            <small>15 minutes ago</small>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                                <hr class="dropdown-divider">-->
<!--                                <a href="#" class="dropdown-item text-center">See all message</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="nav-item dropdown">-->
<!--                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">-->
<!--                                <i class="fa fa-bell me-lg-2"></i>-->
<!--                                <span class="d-none d-lg-inline-flex">Notificatin</span>-->
<!--                            </a>-->
<!--                            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">-->
<!--                                <a href="#" class="dropdown-item">-->
<!--                                    <h6 class="fw-normal mb-0">Profile updated</h6>-->
<!--                                    <small>15 minutes ago</small>-->
<!--                                </a>-->
<!--                                <hr class="dropdown-divider">-->
<!--                                <a href="#" class="dropdown-item">-->
<!--                                    <h6 class="fw-normal mb-0">New user added</h6>-->
<!--                                    <small>15 minutes ago</small>-->
<!--                                </a>-->
<!--                                <hr class="dropdown-divider">-->
<!--                                <a href="#" class="dropdown-item">-->
<!--                                    <h6 class="fw-normal mb-0">Password changed</h6>-->
<!--                                    <small>15 minutes ago</small>-->
<!--                                </a>-->
<!--                                <hr class="dropdown-divider">-->
<!--                                <a href="#" class="dropdown-item text-center">See all notifications</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="nav-item dropdown">-->
<!--                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">-->
<!--                                <img class="rounded-circle me-lg-2" src="/static/img/user.jpg" alt="" style="width: 40px; height: 40px;">-->
<!--                                <span class="d-none d-lg-inline-flex">John Doe</span>-->
<!--                            </a>-->
<!--                            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">-->
<!--                                <a href="#" class="dropdown-item">My Profile</a>-->
<!--                                <a href="#" class="dropdown-item">Settings</a>-->
<!--                                <a href="#" class="dropdown-item">Log Out</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                     {% endif %}-->
                    <div class="nav-item d-none d-lg-inline-flex">
                        <a href="#" class="nav-link" >
                            <i class="fa fa-home me-lg-2">                                </i>
                            <span class="d-none d-lg-inline-flex">الرئيسية</span>
                        </a>
                    </div>
                    <div class="nav-item dropdown d-none d-lg-inline-flex">
                            <a href="{% url 'home:services' %}" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                                <i class="fa fa-th me-lg-2"></i>
                                <span class="d-none d-lg-inline-flex">الخدمات</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                                <a href="{% url 'home:services' %}" class="dropdown-item">
                                    <div class="h6 fw-normal mb-0">كل الخدمات</div>
                                </a>
                                <hr class="dropdown-divider">
                                <a href="#" class="dropdown-item text-center">رؤية كل الخدمات</a>
                            </div>
                        </div>
                    <div class="nav-item d-none d-lg-inline-flex">
                            <a href="#" class="nav-link">
                                <i class="fa fa-book me-lg-2"></i>
                                <span class="d-none d-lg-inline-flex">المكتبة</span>
                            </a>
                    </div>
                    <div class="nav-item d-none d-lg-inline-flex">
                            <a href="#" class="nav-link ">
                                <i class="fa fa-blog me-lg-2"></i>
                                <span class="d-none d-lg-inline-flex">المدونة</span>
                            </a>
                    </div>
                    <div class="nav-item d-none d-lg-inline-flex">
                            <a href="#" class="nav-link ">
                                <i class="fa fa-info me-lg-2"></i>
                                <span class="d-none d-lg-inline-flex">عنا</span>
                            </a>
                    </div>
                </div>
                <form class="d-lg-flex me-5 d-none ">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
            </nav>

home/templates/members/sidebar.html
<div class="sidebar ps-4 pb-3 mt-4">
            <nav class="navbar navbar-light">

                <form class="d-md-flex m-4 border">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
<!--                {% if user.is_authenticated %}-->
<!--                    <div class="d-flex align-items-center me-4 mb-4">-->
<!--                        <div class="position-relative">-->
<!--                            <img class="rounded-circle" src="/static/img/user.jpg" alt="" style="width: 40px; height: 40px;">-->
<!--                            <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>-->
<!--                        </div>-->
<!--                        <div class="me-3">-->
<!--                            <h6 class="mb-0">Jhon Doe</h6>-->
<!--                            <span>طالب</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                {% endif %}-->
                <div class="navbar-nav w-100 ">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-home mx-2"></i>الرئيسية</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-th mx-2"></i>الخدمات</a>
                        <div class="dropdown-menu bg-transparent border-0 text-right">
                            <a href="button.html" class="dropdown-item">بكالوريوس</a>
                            <a href="typography.html" class="dropdown-item">ماجستير</a>
                            <a href="element.html" class="dropdown-item">دكتوراه</a>
                            <a href="element.html" class="dropdown-item">خدمات اخرى</a>
                        </div>
                    </div>
                    <a href="widget.html" class="nav-item nav-link"><i class="fa fa-book mx-2"></i>المكتبة</a>
                    <a href="form.html" class="nav-item nav-link"><i class="fa fa-blog mx-2"></i>المدونة</a>
                    <a href="form.html" class="nav-item nav-link"><i class="fa fa-info mx-2"></i>عنا</a>

                </div>
            </nav>
        </div>

home/templates/members/spinner.html
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>